/*******************************************************************************
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *   
 * Copyright (c) 2021-2023 ETH Zurich.
 *******************************************************************************/
package proof_analyser.unsat_proof;

import java.util.List;

public class Vampire_Unsat_Proof implements Unsat_Proof {
	
	// Contains each line of the unsat-proof generated by Vampire for the input_file.
	private List<String> lines;
	
	public Vampire_Unsat_Proof(List<String> lines) {
		this.lines = lines;
	}
	
	public List<String> getLines(){
		return lines;
	}

	public int get_size() {
		int size = 0;
		for(String line: lines) {
			size += line.length();
		}
		return size;
	}

}
